# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        MainWindow.setMinimumSize(QtCore.QSize(350, 350))
        MainWindow.setMaximumSize(QtCore.QSize(350, 350))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_city = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_city.setGeometry(QtCore.QRect(10, 60, 241, 31))
        self.input_city.setStyleSheet("QLineEdit\n"
"{\n"
"    padding: 0px 0px 0px 5px\n"
"}")
        self.input_city.setObjectName("input_city")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.button_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_search.setGeometry(QtCore.QRect(260, 60, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_search.setFont(font)
        self.button_search.setObjectName("button_search")
        self.label_temperature = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_temperature.setGeometry(QtCore.QRect(10, 110, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_temperature.setFont(font)
        self.label_temperature.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_temperature.setObjectName("label_temperature")
        self.label_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(10, 150, 321, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(72)
        self.label_image.setFont(font)
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("icon.ico"))
        self.label_image.setScaledContents(False)
        self.label_image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.label_condition = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_condition.setGeometry(QtCore.QRect(10, 260, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_condition.setFont(font)
        self.label_condition.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_condition.setObjectName("label_condition")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WeatherApp"))
        self.input_city.setPlaceholderText(_translate("MainWindow", "Enter city"))
        self.label.setText(_translate("MainWindow", "Weather App"))
        self.button_search.setText(_translate("MainWindow", "SEARCH"))
        self.label_temperature.setText(_translate("MainWindow", "Temperature"))
        self.label_condition.setText(_translate("MainWindow", "Condition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
